#▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
#MODULES

admin = {
    'LT': {
        'embed_1': '{} - Profilis',
        'configuration': {
            'extra_1': 'Nėra',
            'extra_2': ' *Narys gali dabar rašyti tik* <#{}> *skiltyje.*',
        },
        'msg_post_1': '\🟢 *Narys* {} *buvo užmutintas iki* _**{}.{}.{} - {}:{}**_.{}',
        'msg_post_2': '\🟢 *Narys* {} *jau yra užmutintas*.',
        'msg_post_3': '\🟢 *Narys* {} *buvo atmutintas.*',
        'msg_post_4': '\🟢 *Narys* {} *jau yra atmutintas*.',
        'msg_success_1': '\🟢 *Jūs sėkmingai pridėjote vartotoją* {} *prie organizatorių.*',
        'msg_success_2': '\🟢 *Jūs sėkmingai pridėjote vartotoją* {} *prie sistemos. Dabar vartotojas turi administratoriaus ir organizatoriaus privilegijas.*',
        'msg_success_3': '\🟢 *Jūs sėkmingai pridėjote vartotoją* {} *prie sistemos. Dabar vartotojas turi buhalterio, administratoriaus ir organizatoriaus privilegijas.*',
        'msg_success_4': '\🟢 *Jūs sėkmingai pašalinote vartotoją* {} *iš sistemos.*',
        'msg_error_1': '\🔴 *Vartotojas* {} *nerastas šiame discordo serveryje.*',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.addorganizer {}**_',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.addadmin {}**_',
        'msg_badformat_3': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.addaccountant {}**_',
        'msg_badformat_4': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.remuser{}**_',
        'msg_badformat_5': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.mute {}**_',
        'msg_badformat_6': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.unmute {}**_',
        'msg_badformat_7': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.post #general tekstas**_',
        'msg_badformat_8': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.showmember {}**_',
        'msg_info_1': '\🟢 *Pavyzdys* _**.addorganizer {}**_',
        'msg_info_2': '\🟢 *Pavyzdys* _**.addadmin {}**_',
        'msg_info_3': '\🟢 *Pavyzdys* _**.addaccountant {}**_',
        'msg_info_4': '\🟢 *Pavyzdys* _**.remuser{}**_',
        'msg_info_5': '\🟢 *Pavyzdys* _**.mute {}**_',
        'msg_info_6': '\🟢 *Pavyzdys* _**.unmute {}**_',
        'msg_info_7': '\🟢 *Pavyzdys* _**.post #general tekstas**_',
        'msg_info_8': '\🟢 *Pavyzdys* _**.showmember {}**_',
        'msg_info_9': '\🟢 *Pavyzdys* _**.mute {}**_ _**1**_',
    },
    'EN': {
        'embed_1': '{} - Profile',
        'configuration': {
            'extra_1': 'Not found',
            'extra_2': ' *Member can only write in* <#{}> *channel.*',
        },
        'msg_post_1': '\🟢 *Member* {} *was muted until* _**{}.{}.{} - {}:{}**_.{}',
        'msg_post_2': '\🟢 *Member* {} *is already muted*.',
        'msg_post_3': '\🟢 *Member* {} *was unmuted.*',
        'msg_post_4': '\🟢 *Member* {} *has already been unmuted*.',
        'msg_success_1': '\🟢 *You have successfully added* {} *to the organizers.*',
        'msg_success_2': '\🟢 *You have successfully added user* {} *to the system. The user now has administrator and organizer privileges.*',
        'msg_success_3': '\🟢 *You have successfully added user* {} *to the system. The user now has accountant, administrator and organizer privileges.*',
        'msg_success_4': '\🟢 *You have successfully removed* {} *from the system.*',
        'msg_error_1': '\🔴 *User* {} *was not found on this discord server.*',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Example* _**.addorganizer {}**_',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Example* _**.addadmin {}**_',
        'msg_badformat_3': '\🟡 *Invalid format.*\n\🟢 *Example* _**.addaccountant {}**_',
        'msg_badformat_4': '\🟡 *Invalid format.*\n\🟢 *Example* _**.remuser{}**_',
        'msg_badformat_5': '\🟡 *Invalid format.*\n\🟢 *Example* _**.mute {}**_',
        'msg_badformat_6': '\🟡 *Invalid format.*\n\🟢 *Example* _**.unmute {}**_',
        'msg_badformat_7': '\🟡 *Invalid format.*\n\🟢 *Example* _**.post #general tekstas**_',
        'msg_badformat_8': '\🟡 *Invalid format.*\n\🟢 *Example* _**.showmember {}**_',
        'msg_info_1': '\🟢 *Example* _**.addorganizer {}**_',
        'msg_info_2': '\🟢 *Example* _**.addadmin {}**_',
        'msg_info_3': '\🟢 *Example* _**.addaccountant {}**_',
        'msg_info_4': '\🟢 *Example* _**.remuser{}**_',
        'msg_info_5': '\🟢 *Example* _**.mute {}**_',
        'msg_info_6': '\🟢 *Example* _**.unmute {}**_',
        'msg_info_7': '\🟢 *Example* _**.post #general tekstas**_',
        'msg_info_8': '\🟢 *Example* _**.showmember {}**_',
        'msg_info_9': '\🟢 *Example* _**.mute {}**_ _**1**_',
    }
}

dc_bank = {
    'LT': {
        'embed_1': '{} - Bankas',
        'configuration': {
            'line': '▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬',
            'title': '**{} sponsorių sąrašas**',
            'top_gp': '**{}** _**›**_ *{} {} gp.*',
            'top_gp_2': '**{}**\n{} _**›**_ {} _**{}**_ *gp.*\n',
            'total_sponsor': '**{} bendra sponsorių suma**',
            'total_gp': '**Iš viso** _**›**_ {} *{} gp.*',
            'extra_1': 'Banko sąskaita',
            'extra_2': 'Nėra',
            'extra_3': '{} banko sąskaita',
            'extra_recipe_0': '*Išrašas* _**›**_ {} _**-{}**_ *gp*.{}\n*Data* _**›**_ _**{}**_.\n\n',
            'extra_recipe_1': '*Išrašas* _**›**_ {} _**+{}**_ *gp*.{}\n*Data* _**›**_ _**{}**_.\n\n',
            'extra_recipe_2': '\n*Priežastis* _**›**_ _**{}**_.',
            'extra_recipe_3': '\n*Priežastis* _**›**_ _**Nėra**_.',
            'extra_recipe_4': '{} išrašai',

        },
        'msg_post_1': '\💰 *Narys* {} *pasponsorino* _**{}**_ *discordo serverį*.{}',
        'msg_post_2': '\💛 *Narys* {} *pasponsorino* _**{}**_ *discordo serverį*. *Suma* _**›**_ _**{}**_ *gp.*',
        'msg_post_1_extra': ' *Išreikšti padėką žaidėjui galite* <#{}> *skiltyje.*',
        'msg_success_1': '\🟢 *Jūs sėkmingai susikūrėte discordo banko sąskaitą. Norint sužinoti daugiau informacijos, rašykite komandą* `.bank`',
        'msg_success_2': '\🟢 *Pervedimas pavyko. Jūs pervedėte* {} _**{}**_ *gp.*',
        'msg_success_3': '\🟢 *Jūs atskaičiavote nuo discordo banko sąskaitos* _**›**_ {} _**{}**_ *gp.*',
        'msg_success_4': '\🟢 *Jūs pridėjote prie discordo banko sąskaitos* {} _**›**_ _**{}**_ *gp.*',
        'msg_success_5': '\🟢 *Jūs sėkmingai sukūrėte banko sąskaitą* {}*.*',
        'msg_1': '<@{}> **|** {} *nori padonatinti* {}  __**{}**__ *gp.* *Pervedimo komanda* _**›**_ `.pay {} {}`',
        'msg_2': '\🗨️ {} *su jumis greitu laiku susisieks administracija.*',
        'msg_3': '\🗨️ *Šiuo metu nėra jokių įrašų.*',
        'msg_4': '\🗨️ *Į jūsų sąskaitą buvo pervesta* _**{}**_ *gp.* *Jūsų discordo banko sąskaitos likutis* _**{}**_ *gp.*',
        'msg_error_1': '\🟢 *Jūs jau turite discordo banko sąskaitą. Norint sužinoti daugiau informacijos, rašykite komandą* `.bank`',
        'msg_error_2': '\🔴 *Jūs neturite discordo banko sąskaitos. Norint susikurti discordo banko sąskaitą, rašykite komandą* `.create`',
        'msg_error_3': '\🔴 {} *neturi discordo banko sąskaitos. Patikrinkite ar teisingai parašėte komandą.*',
        'msg_error_4': '\🟢 {} *jau turite banko sąskaitą.*',
        'msg_error_5': '\🔴 *Sukūrimas nepavyko.* {} *nebuvo rastas* _**{}**_ *serveryje.*',
        'msg_no_config_1': '\🔴 *Nerastas buhalteris. Norint tinkamai sukonfiguruoti discordo serverį, rašykite komandą* `.status`',
        'msg_no_config_2': '\🔴 *Nerasta buhalterijos skiltis. Norint tinkamai sukonfiguruoti discordo serverį, rašykite komandą* `.status`',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.donate 1000000**_',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.minus 1000000 priežastys**_',
        'msg_badformat_3': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.plus 1000000 priežastys**_',
        'msg_badformat_4': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.remote {}**_',
        'msg_badformat_5': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.bankdata {}**_',
        'msg_info_1': '\🟢 *Pavyzdys* _**.donate 1000000**_',
        'msg_info_2': '\🟢 *Pavyzdys* _**.minus 1000000 priežastys**_',
        'msg_info_3': '\🟢 *Pavyzdys* _**.plus 1000000 priežastys**_',
        'msg_info_4': '\🟢 *Pavyzdys* _**.remote {}**_',
        'msg_info_5': '\🟢 *Pavyzdys* _**.bankdata {}**_',
    },
    'EN': {
        'embed_1': '{} - Bank',
        'configuration': {
            'line': '▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬',
            'title': '**List of {} sponsors**',
            'top_gp': '**{}** _**›**_ *{} {} gp.*',
            'top_gp_2': '**{}**\n{} _**›**_ {} _**{}**_ *gp.*\n',
            'total_sponsor': '**{} total donation of sponsors**',
            'total_gp': '**Total** _**›**_ {} *{} gp.*',
            'extra_1': 'Bank account',
            'extra_2': 'Not found',
            'extra_3': '{} bank account',
            'extra_recipe_0': '*Receipt* _**›**_ {} _**-{}**_ *gp*.{}\n*Date* _**›**_ _**{}**_.\n\n',
            'extra_recipe_1': '*Receipt* _**›**_ {} _**+{}**_ *gp*.{}\n*Date* _**›**_ _**{}**_.\n\n',
            'extra_recipe_2': '\n*Reason* _**›**_ _**{}**_.',
            'extra_recipe_3': '\n*Reason* _**›**_ _**Not found**_.',
            'extra_recipe_4': '{} Receipts',

        },
        'msg_post_1': '\💰 *Member* {} *sponsored* _**{}**_ *discord server*.{}',
        'msg_post_2': '\💛 *Member* {} *sponsored* _**{}**_ *discord server*. *Sum* _**›**_ _**{}**_ *gp.*',
        'msg_post_1_extra': ' *You can thank the player in the* <#{}> *channel.*',
        'msg_success_1': '\🟢 *You have successfully created a discord bank account. For more information, write the command* `.bank`',
        'msg_success_2': '\🟢 *The transfer was successful. You transferred* {} _**{}**_ *gp.*',
        'msg_success_3': '\🟢 *You have deducted from the discord bank account* _**›**_ {} _**{}**_ *gp.*',
        'msg_success_4': '\🟢 *You have added to the discord bank account* {} _**›**_ _**{}**_ *gp.*',
        'msg_success_5': '\🟢 *You have successfully created a bank account* {}*.*',
        'msg_1': '<@{}> **|** {} *wants to donate* {}  __**{}**__ *gp.* *Transfer command* _**›**_ `.pay {} {}`',
        'msg_2': '\🗨️ {} *the administration will contact you shortly.*',
        'msg_3': '\🗨️ *There are currently no receipts.*',
        'msg_4': '\🗨️ _**{}**_ *gp was transferred to your account. Your discordo bank account balance is* _**{}**_ *gp.*',
        'msg_error_1': '\🟢 *You already have a discord bank account. For more information, write the command* `.bank`',
        'msg_error_2': '\🔴 *You do not have a discord bank account. To create a discord bank account, type the command* `.create`',
        'msg_error_3': '\🔴 {} *has no discord bank account. Check that you typed the command correctly.*',
        'msg_error_4': '\🟢 {} *already has a bank account.*',
        'msg_error_5': '\🔴 *Creation failed.* {} *was not found on* _**{}**_ *server.*',
        'msg_no_config_1': '\🔴 *No accountant found. To configure the discord server properly, type* `.status`',
        'msg_no_config_2': '\🔴 *No accountant channel found. To configure the discord server properly, type* `.status`',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Example* _**.donate 1000000**_',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Example* _**.minus 1000000 reason**_',
        'msg_badformat_3': '\🟡 *Invalid format.*\n\🟢 *Example* _**.plus 1000000 reason**_',
        'msg_badformat_4': '\🟡 *Invalid format.*\n\🟢 *Example* _**.remote {}**_',
        'msg_badformat_5': '\🟡 *Invalid format.*\n\🟢 *Example* _**.bankdata {}**_',
        'msg_info_1': '\🟢 *Example* _**.donate 1000000**_',
        'msg_info_2': '\🟢 *Example* _**.minus 1000000 reason**_',
        'msg_info_3': '\🟢 *Example* _**.plus 1000000 reason**_',
        'msg_info_4': '\🟢 *Example* _**.remote {}**_',
        'msg_info_5': '\🟢 *Example* _**.bankdata {}**_',
    }
}

organizer = {
    'LT': {
        'embed_1': '{} - Eventai',
        'embed_2': '{} - Organizatorius',
        'configuration': {},
        'embed_configuration': {
            'description': '{} organizuoja **{}** - **{}** valanda {} eventą. Norintiems dalyvauti, prašome paspausti ant {} emoji.',
            'field_1': 'Papildoma informacija',
            'field_2': 'Event komandos',
            'field_3': '{} | ID: {}',
            'value_3': '\📅 `Data › {}.`\n\⌚ `Laikas › {} valanda.`\n\⭐ `Organizatorius › `**<@{}>**.\n\👥 `Dalyvių › {}.`',
            'value_4': '\📅 `Data › {} - {}.`\n\⌚ `Laikas › {} - {} valanda.`\n\⭐ `Organizatorius ›` **<@{}>**.\n\👥 `Dalyvių › {}.`',
            'value_5': '\📅 `Data › {}.`\n\⌚ `Laikas › {} valanda.`\n\🏆 `Tikslas › {} xp.`\n\⭐ `Organizatorius ›` **<@{}>**.\n\👥 `Dalyvių › {}.`',
            'extra_1': 'Norint sužinoti organizuojamų eventų sąrašą, rašykite komandą `.events`',
            'extra_2': '*Daugiau informacijos rasite skiltyje* <#{}>.',
        },
        'msg_post_1': '\📣 *Dėmesio <@&{}>! {} eventas prasidėjo. Daugiau informacijos <#{}> skiltyje arba parašę komandą `.events`*',
        'msg_post_2': '\📣 *Dėmesio <@&{}>! Po valandos organizatorius {} planuoja {} eventą. Visi norintys ruošiamės ir jungiamės į pagrindinį pokalbių kanalą. Daugiau informacijos <#{}> skiltyje arba parašę komandą `.events`.*',
        'msg_post_3': '\📣 *Dėmesio! {} valanda organizatorius {} planuoja {} eventą. Daugiau informacijos <#{}> skiltyje arba parašę komandą `.events`*',
        'msg_success_1': '\🟢 *Jūs sėkmingai užregistravote eventą.*',
        'msg_success_2': '\🟢 *Jūs sėkmingai ištrynėte eventą.*',
        'msg_1': '\🗨️ *Pridėtas {} eventas. Daugiau informacijos skiltyje* <#{}>.',
        'msg_2': '\🗨️ *Šiuo metu nėra organizuojamų eventų.*',
        'msg_error_1': '\🔴 *Nerasta eventų skiltis. Norint tinkamai sukonfiguruoti discordo serverį, rašykite komandą* `.status`',
        'msg_error_2': '\🔴 *Eventas nerastas, bandykite dar kartą.*',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Naudokyt generatorių* *https://origin.clan.su/generator.html*. *Minutės ir metai neturi jokios reikšmės.*',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.remove 158956**_\n\🟢 *Norint sužinoti evento ID, rašykite komandą* `.events`',
    },
    'EN': {
        'embed_1': '{} - Events',
        'embed_2': '{} - Organizer',
        'configuration': {},
        'embed_configuration': {
            'description': '{} organizes **{}** - **{}** hour {} event. To participate, please click on {} emoji.',
            'field_1': 'Additional information',
            'field_2': 'Event commands',
            'field_3': '{} | ID: {}',
            'value_3': '\📅 `Date › {}.`\n\⌚ `Time › {} hour.`\n\⭐ `Organizer › `**<@{}>**.\n\👥 `Participants › {}.`',
            'value_4': '\📅 `Date › {} - {}.`\n\⌚ `Time › {} - {} hour.`\n\⭐ `Organizer ›` **<@{}>**.\n\👥 `Participants › {}.`',
            'value_5': '\📅 `Date › {}.`\n\⌚ `Time › {} hour.`\n\🏆 `Targer › {} xp.`\n\⭐ `Organizer ›` **<@{}>**.\n\👥 `Participants › {}.`',
            'extra_1': 'For a list of events, type `.events`',
            'extra_2': '*See* <#{}> *for more information.*',
        },
        'msg_post_1': '\📣 *Attention* <@&{}>! *{} event has started. For more information, see* <#{}> *or type* `.events`',
        'msg_post_2': '\📣 *Attention* <@&{}>! *An hour later, the organizer {} is planning a {} event. Please get ready and connect to the general voice channel. For more information, see* <#{}> *or type* `.events`.',
        'msg_post_3': "\📣 *Attention! At {} o'clock the organizer {} is planning a {} event. For more information, see* <#{}> *or type* `.events`",
        'msg_success_1': '\🟢 *You have successfully registered an event*',
        'msg_success_2': '\🟢 *You have successfully deleted an event.*',
        'msg_1': '\🗨️ *Added {} event. More information in the channel* <#{}>!',
        'msg_2': '\🗨️ *There are currently no events.*',
        'msg_error_1': '\🔴 *No events channel found. To configure the discord server properly, type* `.status`',
        'msg_error_2': '\🔴 *Event not found, please try again.*',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Please use a generator* *https://origin.clan.su/generator.html*. *Minutes and years do not matter.*',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Example* _**.remove 158956**_\n\🟢 *To find out the event ID, type the command* `.events`',
    }
}

rsn_register = {
    'LT': {
        'embed_1': '{} - RSN sąrašas',
        'configuration': {'module_name': 'RSN Sąrašas', 'rsn_list': '_**{}.**_ _*{}*_ _**|**_ _**Data**_ _**|**_ *{}*\n', 'rsn_false': 'Nėra.'},
        'msg_success_1': '\🟢 *Registracija pavyko. Jūs užregistravote RSN* _**{}**_.',
        'msg_success_2': '\🟢 *Registracija pavyko. Jūs atnaujinote savo RSN į* _**{}**_.',
        'msg_error_1': '\🔴 *Registracija nepavyko. RSN* _**›**_ *{} nerastas sistemoje. Prašome palaukti pora minučių ir bandyti dar kartą.*',
        'msg_error_2': '\🔴 *Paieška nepavyko.* {} *nebuvo rastas* _**{}**_ *serveryje arba nėra užregistravęs RSN.*',
        'msg_info_1': '\🟢 *Pavyzdys* _**.checkrsn {}**_',
        'msg_info_2': '\🟢 *Pavyzdys* _**.rsn Zezima**_',
    },
    'EN': {
        'embed_1': '{} - RSN List',
        'configuration': {'module_name': 'RSN List', 'rsn_list': '_**{}.**_ _*{}*_ _**|**_ _**Date**_ _**|**_ *{}*\n', 'rsn_false': 'Not found.'},
        'msg_success_1': '\🟢 *Registration successful. You have registered your RSN* _**{}**_.',
        'msg_success_2': '\🟢 *Registration successful. You have updated your RSN to* _**{}**_.',
        'msg_error_1': '\🔴 *Registration failed. RSN* _**›**_ *{} not found in system. Please wait a couple of minutes and try again.*',
        'msg_error_2': '\🔴 *Search failed.* {} *was not found on the* _**{}**_ *server or has not registered an RSN.*',
        'msg_info_1': '\🟢 *Example* _**.checkrsn {}**_',
        'msg_info_2': '\🟢 *Example* _**.rsn Zezima**_',
    }
}

xp_tracker = {
    'LT': {
        'embed_1': '{} - Organizatorius',
        'embed_2': '{} - XP Eventai',
        'embed_3': '{} - {} XP evento topai',
        'embed_4': '{} - XP evento nugalėtojai',
        'extra_1': '\🥇 **{}** _**›**_ {}',
        'extra_2': '\🏆 **{}** _**›**_ {}',
        'extra_3': '\🏆 **{}** _**›**_ {} | RSN: {}',
        'extra_4': 'nėra',
        'configuration': {'rsn': 'MANO RSN: ', 'rank': 'MANO RANKAS: ', 'xp': 'PAKELTA: ', 'current_xp': '**{}**\n{} _**›**_ _**{}**_ _**›**_ {} xp.\n', 'total_xp': '\n**Iš viso** _**›**_ *{} xp.*\n', 'rush_point': '*Žaidėjas laimės eventą pasiekęs* _**{}**_ *xp.*'},
        'description_1': '{} organizuoja **{}** - **{}** valanda {} eventą. Eventas vyks iki **{}** - **{}** valandos. {}',
        'msg_success_1': '\🟢 *Jūs sėkmingai užregistravote eventą.*',
        'msg_success_2': '\🟢 *Jūs sėkmingai ištrynėte eventą.*',
        'msg_success_4': '\🟢 *Jūsų xp buvo atnaujintas. Norint sužinoti dabartinį xp, rašykite komandą* `.xprank`',
        'msg_post_1': '\📣 *Pridėtas* _**{}**_ *XP eventas. Daugiau informacijos skiltyje* <#{}>.',
        'msg_post_2': '\📣 *Dėmesio!* _**{}**_ *XP eventas pasibaigė! Prašome įteikti pirmos vietos prizą žaidėjui* {}.',
        'msg_post_3': '\📣 *Dėmesio!* _**{}**_ *XP eventas pasibaigė! Prašome įteikti atitinkamą prizą žaidėjui* {}.',
        'msg_post_4': '\📣 *Dėmesio!* _**{}**_ *XP eventas prasidėjo!*',
        'msg_post_5': '\📣 *Dėmesio!* _**{}**_ *XP eventas pasibaigė. Topus rasite* <#{}> *skiltyje!*',
        'msg_post_6': '\📣 *Dėmesio! Atidaryta* _**{}**_ *XP evento dalyvių registracija. Daugiau informacijos skiltyje* <#{}>!',
        'msg_post_7': '\📣 *Dėmesio!* _**{}**_ *statistika atnaujinta! Topus rasite skiltyje skiltyje* <#{}>!',
        'msg_1': '\🗨️ *Žaidėjas* __*{}*__ *pridėtas į XP eventą. Daugiau informacijos skiltyje* <#{}>!',
        'msg_2': '\🗨️ *Šiuo metu nėra xp eventų.*',
        'msg_3': '\🗨️ *Jūs jau užregistravote RSN* _**{}**_!',
        'msg_4': '\🗨️ *Šiuo metu nėra prisiregistravusių žaidėjų prie XP evento.*',
        'msg_5': '\🗨️ *Šiuo metu nėra prasidėjusių XP eventų.*',
        'msg_6': '\🗨️ *Jūs užregistravote prie {} evento.*',
        'msg_7': '\🗨️ *Jūs sėkmingai buvote užsiregistruotas prie eventų.*',
        'msg_error_1': '\🔴 *Oficialus runescape hiscores neatsinaujina, bandykite dar kartą.*',
        'msg_error_2': '\🔴 *Toks RSN neegzistuoja. Įsitikinkite, kad RSN rašote teisingai ir bandykite dar kartą.*',
        'msg_error_3': '\🔴 *Oficialus runescape hiscores neatsinaujina. Prašome palaukti pora minučių ir bandyti dar kartą.*',
        'msg_error_4': '\🔴 *Jūsų RSN* {} *nerodo oficialiame runescape hiscores puslapyje. Prašome palaukti pora minučių ir bandyti dar kartą.*',
        'msg_error_5': '\🔴 *Jūs esate neužsiregistruotas XP evente. Norint užsiregistruoti XP evente, rašykite komandą* `.axp`',
        'msg_error_6': '\🔴 *Žaidėjas* {} *nėra užsiregistravęs XP evente.*',
        'msg_error_7': '\🔴 *Dėmesio!* {} *XP eventas pasibaigė! Deja žaidėjas* {} *su RSN* {} *nėra* {} *discordo serveryje*.',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Naudokyt generatorių* *https://origin.clan.su/generator.html*. *Minutės ir metai neturi jokios reikšmės.*',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.axp Zezima**_',
    },
    'EN': {
        'embed_1': '{} - Organizer',
        'embed_2': '{} - XP Events',
        'embed_3': '{} - {} XP event top',
        'embed_4': '{} - XP event winners',
        'extra_1': '\🥇 **{}** _**›**_ {}',
        'extra_2': '\🏆 **{}** _**›**_ {}',
        'extra_3': '\🏆 **{}** _**›**_ {} | RSN: {}',
        'extra_4': 'not setted',
        'configuration': {'rsn': 'MY RSN: ', 'rank': 'MY RANK: ', 'xp': 'XP: ', 'current_xp': '**{}**\n{} _**›**_ _**{}**_ _**›**_ {} xp.\n', 'total_xp': '\n**Total** _**›**_ *{} xp.*\n', 'rush_point': '*The player will win the event by reaching* _**{}** _ *xp.*', 'boss_list': 'Boss list'},
        'description_1': '{} organizes **{}** - **{}** hour {} event. The event will run until **{}** - **{}** hour. {}',
        'msg_success_1': '\🟢 *You have successfully registered an event.*',
        'msg_success_2': '\🟢 *You have successfully deleted an event.*',
        'msg_success_4': '\🟢 *Your xp has been updated. To find out the current xp, type the command* `.xprank`',
        'msg_post_1': '\📣 *Added* _**{}**_ *XP event. More information in the channel* <#{}>.',
        'msg_post_2': '\📣 *Attention!* _**{}**_ *XP event is over! Please present the first place prize to the player* {}.',
        'msg_post_3': '\📣 *Attention!* _**{}**_ *XP event is over! Please present the prize to the player* {}.',
        'msg_post_4': '\📣 *Attention!* _**{}**_ *XP event has started!*',
        'msg_post_5': '\📣 *Attention!* _**{}**_ *XP event is over. Top players you can find in* <#{}> *channel!*',
        'msg_post_6': '\📣 *Attention! Registration for* _**{}**_ *XP event has been opened. More information in the channel* <#{}>!',
        'msg_post_7': '\📣 *Attention!* _**{}**_ *statistics updated! You can find the tops in the channel* <#{}>!',
        'msg_1': '\🗨️ *Player* __*{}*__ *added to XP event. More information in the channel* <#{}>!',
        'msg_2': '\🗨️ *There are currently no xp events.*',
        'msg_3': '\🗨️ *You have already registered an RSN* _**{}**_!',
        'msg_4': '\🗨️ *There are currently no players registered for the XP event.*',
        'msg_5': '\🗨️ *There are currently no XP events started.*',
        'msg_6': '\🗨️ *You have registered for {} event.*',
        'msg_7': '\🗨️ *You have successfully registered for events.*',
        'msg_error_1': '\🔴 *The official runescape hiscores are not updated, please try again.*',
        'msg_error_2': '\🔴 *Such an RSN does not exist. Make sure you are writing the RSN correctly and try again.*',
        'msg_error_3': '\🔴 *The official runescape hiscores are not updated. Please wait a couple of minutes and try again.*',
        'msg_error_4': '\🔴 *Your RSN* {} *does not appear on the official runescape hiscores page. Please wait a couple of minutes and try again.*',
        'msg_error_5': '\🔴 *You are not registered for an XP event. To register for the XP event, type* `.axp`',
        'msg_error_6': '\🔴 *Player* {} *has not registered for XP event.*',
        'msg_error_7': '\🔴 *Attention!* {} *XP event is over! Unfortunately the player* {} *with RSN* {} *is not on the* {} *discord server*.',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Please use a generator* *https://origin.clan.su/generator.html*. *Minutes and years do not matter.*',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Example* _**.axp Zezima**_',
    }
}

kc_tracker = {
    'LT': {
        'embed_1': '{} - Organizatorius',
        'embed_2': '{} - KC Eventai',
        'embed_3': '{} - {} KC evento topai',
        'embed_4': '{} - KC evento nugalėtojai',
        'extra_1': '\🥇 **{}** _**›**_ {}',
        'extra_2': '\🏆 **{}** _**›**_ {}',
        'extra_3': '\🏆 **{}** _**›**_ {} | RSN: {}',
        'extra_4': 'nėra',
        'configuration': {'rsn': 'MANO RSN: ', 'rank': 'MANO RANKAS: ', 'kc': 'KC: ', 'current_kc': '**{}**\n{} _**›**_ _**{}**_ _**›**_ {} kc.\n', 'total_kc': '\n**Iš viso** _**›**_ *{} kc.*\n', 'rush_point': '*Žaidėjas laimės eventą pasiekęs* _**{}**_ *kc.*', 'boss_list': 'Bosų sąrašas'},
        'description_1': '{} organizuoja **{}** - **{}** valanda {} eventą. Eventas vyks iki **{}** - **{}** valandos. {}',
        'msg_success_1': '\🟢 *Jūs sėkmingai užregistravote eventą.*',
        'msg_success_2': '\🟢 *Jūs sėkmingai ištrynėte eventą.*',
        'msg_success_4': '\🟢 *Jūsų kc buvo atnaujintas. Norint sužinoti dabartinį kc, rašykite komandą* `.kcrank`',
        'msg_post_1': '\📣 *Pridėtas* _**{}**_ *KC eventas. Daugiau informacijos skiltyje* <#{}>.',
        'msg_post_2': '\📣 *Dėmesio!* _**{}**_ *KC eventas pasibaigė! Prašome įteikti pirmos vietos prizą žaidėjui* {}.',
        'msg_post_3': '\📣 *Dėmesio!* _**{}**_ *KC eventas pasibaigė! Prašome įteikti atitinkamą prizą žaidėjui* {}.',
        'msg_post_4': '\📣 *Dėmesio!* _**{}**_ *KC eventas prasidėjo!*',
        'msg_post_5': '\📣 *Dėmesio!* _**{}**_ *KC eventas pasibaigė. Topus rasite* <#{}> *skiltyje!*',
        'msg_post_6': '\📣 *Dėmesio! Atidaryta* _**{}**_ *KC evento dalyvių registracija. Daugiau informacijos skiltyje* <#{}>!',
        'msg_post_7': '\📣 *Dėmesio!* _**{}**_ *statistika atnaujinta! Topus rasite skiltyje skiltyje* <#{}>!',
        'msg_1': '\🗨️ *Žaidėjas* __*{}*__ *pridėtas į KC eventą. Daugiau informacijos skiltyje* <#{}>!',
        'msg_2': '\🗨️ *Šiuo metu nėra kc eventų.*',
        'msg_3': '\🗨️ *Jūs jau užregistravote RSN* _**{}**_!',
        'msg_4': '\🗨️ *Šiuo metu nėra prisiregistravusių žaidėjų prie KC evento.*',
        'msg_5': '\🗨️ *Šiuo metu nėra prasidėjusių KC eventų.*',
        'msg_6': '\🗨️ *Jūs užregistravote prie {} evento.*',
        'msg_7': '\🗨️ *Jūs sėkmingai buvote užsiregistruotas prie eventų.*',
        'msg_error_1': '\🔴 *Oficialus runescape hiscores neatsinaujina, bandykite dar kartą.*',
        'msg_error_2': '\🔴 *Toks RSN neegzistuoja. Įsitikinkite, kad RSN rašote teisingai ir bandykite dar kartą.*',
        'msg_error_3': '\🔴 *Oficialus runescape hiscores neatsinaujina. Prašome palaukti pora minučių ir bandyti dar kartą.*',
        'msg_error_4': '\🔴 *Jūsų RSN* {} *nerodo oficialiame runescape hiscores puslapyje. Prašome palaukti pora minučių ir bandyti dar kartą.*',
        'msg_error_5': '\🔴 *Jūs esate neužsiregistruotas KC evente. Norint užsiregistruoti KC evente, rašykite komandą* `.akc`',
        'msg_error_6': '\🔴 *Žaidėjas* {} *nėra užsiregistravęs KC evente.*',
        'msg_error_7': '\🔴 *Dėmesio!* {} *KC eventas pasibaigė! Deja žaidėjas* {} *su RSN* {} *nėra* {} *discordo serveryje*.',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Naudokyt generatorių* *https://origin.clan.su/generator.html*. *Minutės ir metai neturi jokios reikšmės.*',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.akc Zezima**_',
    },
    'EN': {
        'embed_1': '{} - Organizer',
        'embed_2': '{} - KC Events',
        'embed_3': '{} - {} KC event top',
        'embed_4': '{} - KC event winners',
        'extra_1': '\🥇 **{}** _**›**_ {}',
        'extra_2': '\🏆 **{}** _**›**_ {}',
        'extra_3': '\🏆 **{}** _**›**_ {} | RSN: {}',
        'extra_4': 'not setted',
        'configuration': {'rsn': 'MY RSN: ', 'rank': 'MY RANK: ', 'kc': 'KC: ', 'current_kc': '**{}**\n{} _**›**_ _**{}**_ _**›**_ {} kc.\n', 'total_kc': '\n**Total** _**›**_ *{} kc.*\n', 'rush_point': '*The player will win the event by reaching* _**{}** _ *kc.*', 'boss_list': 'Boss list'},
        'description_1': '{} organizes **{}** - **{}** hour {} event. The event will run until **{}** - **{}** hour. {}',
        'msg_success_1': '\🟢 *You have successfully registered an event.*',
        'msg_success_2': '\🟢 *You have successfully deleted an event.*',
        'msg_success_4': '\🟢 *Your kc has been updated. To find out the current kc, type the command* `.kcrank`',
        'msg_post_1': '\📣 *Added* _**{}**_ *KC event. More information in the channel* <#{}>.',
        'msg_post_2': '\📣 *Attention!* _**{}**_ *KC event is over! Please present the first place prize to the player* {}.',
        'msg_post_3': '\📣 *Attention!* _**{}**_ *KC event is over! Please present the prize to the player* {}.',
        'msg_post_4': '\📣 *Attention!* _**{}**_ *KC event has started!*',
        'msg_post_5': '\📣 *Attention!* _**{}**_ *KC event is over. Top players you can find in* <#{}> *channel!*',
        'msg_post_6': '\📣 *Attention! Registration for* _**{}**_ *KC event has been opened. More information in the section* <#{}>!',
        'msg_post_7': '\📣 *Attention!* _**{}**_ *statistics updated! You can find the tops in the channel* <#{}>!',
        'msg_1': '\🗨️ *Player* __*{}*__ *added to KC event. More information in the channel* <#{}>!',
        'msg_2': '\🗨️ *There are currently no kc events.*',
        'msg_3': '\🗨️ *You have already registered an RSN* _**{}**_!',
        'msg_4': '\🗨️ *There are currently no players registered for the KC event.*',
        'msg_5': '\🗨️ *There are currently no KC events started.*',
        'msg_6': '\🗨️ *You have registered for {} event.*',
        'msg_7': '\🗨️ *You have successfully registered for events.*',
        'msg_error_1': '\🔴 *The official runescape hiscores are not updated, please try again.*',
        'msg_error_2': '\🔴 *Such an RSN does not exist. Make sure you are writing the RSN correctly and try again.*',
        'msg_error_3': '\🔴 *The official runescape hiscores are not updated. Please wait a couple of minutes and try again.*',
        'msg_error_4': '\🔴 *Your RSN* {} *does not appear on the official runescape hiscores page. Please wait a couple of minutes and try again.*',
        'msg_error_5': '\🔴 *You are not registered for an KC event. To register for the KC event, type* `.akc`',
        'msg_error_6': '\🔴 *Player* {} *has not registered for KC event.*',
        'msg_error_7': '\🔴 *Attention!* {} *KC event is over! Unfortunately the player* {} *with RSN* {} *is not on the* {} *discord server*.',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Please use a generator* *https://origin.clan.su/generator.html*. *Minutes and years do not matter.*',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Example* _**.akc Zezima**_',
    }
}

server = {
    'LT': {
        'embed_1': '{} - Serveris',
        'embed_2': '{} - Privatus pluginai',
        'embed_3': '{} - Sveiki!',
        'configuration': {
            'private': '_**Pluginas**_ _**›**_ *{}*\n_**Savininkas**_ _**›**_ {}\n_**Komandos**_ _**›**_ {}',
            'status_server': '<#{}> {}\n',
            'status_server_field_1': 'Serverio skiltis',
            'status_server_field_2': 'Statusų reikšmės',
            'status_server_value_2': '{} _**‹**_ Aktyvuotas\n{} _**‹**_ Nesukonfigūruotas\n{} _**‹**_ Deaktyvuotas\n',
            'status_server_field_3': 'Daugiau informacijos',
            'status_server_value_3': '*Norint sužinoti daugiau apie privačius Origin pluginus, rašykite komandą* `.private`',
            'status_config_field_1': '{} plugino konfigūracija',
            'status_config_field_2': 'Valdymo pultas',
            'extra_1': 'Nėra',
            'extra_2': 'Nėra informacijos.',
            'active': 'Aktyvuotas',
            'deactive': 'Deaktyvuotas'

        },
        'server.config.admin_1': '**Administracijos skiltis** _**›**_ {}\n```.config channel admin #administracija```\n**Ban rolė** _**›**_ {}\n```.setup admin SECTION1 BAN @role```',
        'server.config.dc_bank_1': '**Buhalterijos skiltis** _**›**_ {}\n```.config channel dc_bank #buhalterija```\n**Sponsorių skiltis** _**›**_ {}\n```.config channel sponsor #sponsoriai```\n**Padėkų skiltis** _**›**_ {}\n```.config channel thanks #padėkos```\n**(SB) Pagrindinis buhalteris** _**›**_ {}\n```.setup dc_bank SECTION1 ADMIN @user```\n**[ TOP 1 ] sponsoriaus rolė** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_1 @role```\n**[ TOP 2 ] sponsoriaus rolė** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_2 @role```\n**[ TOP 3 ] sponsoriaus rolė** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_3 @role```\n**[ TOP 4 ] sponsoriaus rolė** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_4 @role```\n**[ TOP 5 ] sponsoriaus rolė** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_5 @role```',
        'server.config.dc_bank_2': '**[ TOP 1 ] sponsoriaus suma** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_1_COUNT 500000000```\n**[ TOP 2 ] sponsoriaus suma** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_2_COUNT 400000000```\n**[ TOP 3 ] sponsoriaus suma** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_3_COUNT 300000000```\n**[ TOP 4 ] sponsoriaus suma** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_4_COUNT 200000000```\n**[ TOP 5 ] sponsoriaus suma** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_5_COUNT 100000000```\n**Spamas pokalbių skiltyje [ 0 - Ne | 1 - Taip ]** _**›**_ {}\n```.setup dc_bank CHANNEL_PERMISSIONS STATUS 1```',
        'server.config.organizer_1': '**Eventų skiltis** _**›**_ {}\n```.config channel events #eventai```\n**Event rolė** _**›**_ {}\n```.setup organizer SECTION1 EVENT_ROLE @role```\n**Spamas pokalbių skiltyje [ 0 - Ne | 1 - Taip ]** _**›**_ {}\n```.setup organizer CHANNEL_PERMISSIONS STATUS 1```\n**Automatinių žinučių laikrodis** _**›**_ *Kas* {} *h*\n```.setup organizer NOTIFICATION_TIMER HOURS 1```',
        'server.config.rsn_register_1': '**Registracijos skiltis** _**›**_ {}\n```.config channel rsn #registracija```\n**Registracijos rolė** _**›**_ {}\n```.setup rsn_register SECTION1 ROLE @role```',
        'server.config.server_1': '**Pagrindinė pokalbių skiltis** _**›**_ {}\n```.config channel chat0 #pagrindinis```\n**Boto skiltis** _**›**_ {}\n```.config channel chat1 #boto-skiltis```\n**Serverio kalba** _**›**_ {}\n**Serverio laikas** _**›**_ {}\n[Paspauskite, kad pakeisti serverio nustatymus](https://origin.clan.su/setup.html)',
        'server.config.xp_tracker_1': '**Eventų skiltis** _**›**_ {}\n```.config channel events #eventai```\n**XP eventų skiltis** _**›**_ {}\n```.config channel xp_event #xp_event```\n**Evento laimėtojo rolė** _**›**_ {}\n```.setup xp_tracker SECTION1 EVENT_WINNER @role```\n**Event rolė** _**›**_ {}\n```.setup xp_tracker SECTION1 EVENT_ROLE @role```\n**Spamas pokalbių skiltyje [ 0 - Ne | 1 - Taip ]** _**›**_ {}\n```.setup xp_tracker CHANNEL_PERMISSIONS STATUS 1```\n**Automatinių žinučių laikrodis** _**›**_ *Kas* {} *h*\n```.setup xp_tracker NOTIFICATION_TIMER HOURS 1```',
        'server.config.kc_tracker_1': '**Eventų skiltis** _**›**_ {}\n```.config channel events #eventai```\n**KC eventų skiltis** _**›**_ {}\n```.config channel kc_event #xp_event```\n**Evento laimėtojo rolė** _**›**_ {}\n```.setup kc_tracker SECTION1 EVENT_WINNER @role```\n**Event rolė** _**›**_ {}\n```.setup kc_tracker SECTION1 EVENT_ROLE @role```\n**Spamas pokalbių skiltyje [ 0 - Ne | 1 - Taip ]** _**›**_ {}\n```.setup kc_tracker CHANNEL_PERMISSIONS STATUS 1```\n**Automatinių žinučių laikrodis** _**›**_ *Kas* {} *h*\n```.setup kc_tracker NOTIFICATION_TIMER HOURS 1```',
        'server.config.vote_1': '**Votemute leidimo rolė** _**›**_ {}\n```.setup vote SECTION1 RESTRICTION @role```\n**Minimalus balsų skaičius** _**›**_ {}\n```.setup vote SECTION2 COUNT 10```',
        'server.config.active_deactive': '\🟢 Aktyvacija ```.active {}```\🟡 Deaktyvacija ```.deactive {}```',
        'msg_success_1': '\🟢 *Jūs sėkmingai užregistravote* _**{}**_ *skiltį.*',
        'msg_success_2': '\🟢 *Pakeitimas pavyko.*',
        'msg_success_3': '\🟢 *Jūs sėkmingai aktyvavote pluginą.*',
        'msg_success_4': '\🟢 *Jūs sėkmingai deaktyvavote pluginą.*',
        'msg_success_5': '\🟢 *Jūs sėkmingai sukonfigūravote discordo serverį. Dabar galite konfigūruoti serveri parašę komandą.* `.status`',
        'msg_1': '\🗨️ *Norint sužinoti daugiau informacijos, rašykite komandą* `.status`',
        'msg_error_1': '\🔴 _**{}**_ *skilties nėra šiame discordo serveryje.*',
        'msg_error_2': '\🔴 _**{}**_ *pluginas nerastas sistemoje.*',
        'msg_error_3': '\🔴 _**{}**_ *argumentas nerastas sistemoje. Prašome patikrinti ar teisingai rašote komandą ir bandykite dar kartą.*',
        'msg_error_4': '\🔴 *Pakeitimas nepavyko. Patikrinkite ar parašėte komandą teisingai.*',
        'msg_error_5': '\🔴 *Modulio aktyvacija nepavyko. Prašome patikrinti plugino konfigūraciją.*',
        'msg_badformat_1': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.config channel chat0 #general**_',
        'msg_badformat_2': '\🟡 *Netinkamas formatas.*\n\🟢 *Naudokite serverio nustatymų pultą* *https://origin.clan.su/setup.html*.',
    },
    'EN': {
        'embed_1': '{} - Server',
        'embed_2': '{} - Private plugins',
        'embed_3': '{} - Welcome!',
        'configuration': {
            'private': '_**Plugin**_ _**›**_ *{}*\n_**Owner**_ _**›**_ {}\n_**Commands**_ _**›**_ {}',
            'status_server': '<#{}> {}\n',
            'status_server_field_1': 'Server channels',
            'status_server_field_2': 'Status explanation',
            'status_server_value_2': '{} _**‹**_ Activated\n{} _**‹**_ Not configured\n{} _**‹**_ Deactivated\n',
            'status_server_field_3': 'Additional information',
            'status_server_value_3': '*To learn more about private Origin plugins, type* `.private`',
            'status_config_field_1': '{} plugin configuration',
            'status_config_field_2': 'Control panel',
            'extra_1': 'Not found',
            'extra_2': 'No information.',
            'active': 'Activated',
            'deactive': 'Deactivated'

        },
        'server.config.admin_1': '**Admin channel** _**›**_ {}\n```.config channel admin #admin_channel```\n**Ban role** _**›**_ {}\n```.setup admin SECTION1 BAN @role```',
        'server.config.dc_bank_1': '**Accounting channel** _**›**_ {}\n```.config channel dc_bank #accounting_channel```\n**Sponsor channel** _**›**_ {}\n```.config channel sponsor #sponsor_channel```\n**Thanks channel** _**›**_ {}\n```.config channel thanks #thanks_channel```\n**(SB) Accountant** _**›**_ {}\n```.setup dc_bank SECTION1 ADMIN @user```\n**[ TOP 1 ] role of sponsor** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_1 @role```\n**[ TOP 2 ] role of sponsor** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_2 @role```\n**[ TOP 3 ] role of sponsor** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_3 @role```\n**[ TOP 4 ] role of sponsor** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_4 @role```\n**[ TOP 5 ] role of sponsor** _**›**_ {}\n```.setup dc_bank SECTION2 DISCORD_TOP_5 @role```',
        'server.config.dc_bank_2': '**[ TOP 1 ] donation amount** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_1_COUNT 500000000```\n**[ TOP 2 ] donation amount** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_2_COUNT 400000000```\n**[ TOP 3 ] donation amount** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_3_COUNT 300000000```\n**[ TOP 4 ] donation amount** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_4_COUNT 200000000```\n**[ TOP 5 ] donation amount** _**›**_ {}\n```.setup dc_bank SECTION3 DISCORD_TOP_5_COUNT 100000000```\n**Spam in the general chat [ 0 - No | 1 - Yes ]** _**›**_ {}\n```.setup dc_bank CHANNEL_PERMISSIONS STATUS 1```',
        'server.config.organizer_1': '**Event channel** _**›**_ {}\n```.config channel events #event_channel```\n**Event role** _**›**_ {}\n```.setup organizer SECTION1 EVENT_ROLE @role```\n**Spam in the general chat [ 0 - No | 1 - Yes ]** _**›**_ {}\n```.setup organizer CHANNEL_PERMISSIONS STATUS 1```\n**Spam every** *{} hours*\n```.setup organizer NOTIFICATION_TIMER HOURS 1```',
        'server.config.rsn_register_1': '**Registration channel** _**›**_ {}\n```.config channel rsn #rsn_channel```\n**Registration role** _**›**_ {}\n```.setup rsn_register SECTION1 ROLE @role```',
        'server.config.server_1': '**General channel** _**›**_ {}\n```.config channel chat0 #general```\n**Bot channel** _**›**_ {}\n```.config channel chat1 #bot-channel```\n**Server language** _**›**_ {}\n**Server time** _**›**_ {}\n[Click to change server settings](https://origin.clan.su/setup.html)',
        'server.config.xp_tracker_1': '**Event channel** _**›**_ {}\n```.config channel events #event_channel```\n**XP event channel** _**›**_ {}\n```.config channel xp_event #xp_event```\n**Event winner role** _**›**_ {}\n```.setup xp_tracker SECTION1 EVENT_WINNER @role```\n**Event role** _**›**_ {}\n```.setup xp_tracker SECTION1 EVENT_ROLE @role```\n**Spam in the general chat [ 0 - No | 1 - Yes ]** _**›**_ {}\n```.setup xp_tracker CHANNEL_PERMISSIONS STATUS 1```\n**Spam every** *{} hours*\n```.setup xp_tracker NOTIFICATION_TIMER HOURS 1```',
        'server.config.kc_tracker_1': '**Event channel** _**›**_ {}\n```.config channel events #event_channel```\n**KC event channel** _**›**_ {}\n```.config channel kc_event #kc_event```\n**Event winner role** _**›**_ {}\n```.setup kc_tracker SECTION1 EVENT_WINNER @role```\n**Event role** _**›**_ {}\n```.setup kc_tracker SECTION1 EVENT_ROLE @role```\n**Spam in the general chat [ 0 - No | 1 - Yes ]** _**›**_ {}\n```.setup kc_tracker CHANNEL_PERMISSIONS STATUS 1```\n**Spam every** *{} hours*\n```.setup kc_tracker NOTIFICATION_TIMER HOURS 1```',
        'server.config.vote_1': '**Votemute access role** _**›**_ {}\n```.setup vote SECTION1 RESTRICTION @role```\n**Minimal vote count** _**›**_ {}\n```.setup vote SECTION2 COUNT 10```',
        'server.config.active_deactive': '\🟢 Activate ```.active {}```\🟡 Deactivate ```.deactive {}```',
        'msg_success_1': '\🟢 *You have successfully registered the* _**{}**_ *channel.*',
        'msg_success_2': '\🟢 *The change was successful.*',
        'msg_success_3': '\🟢 *You have successfully activated the plugin.*',
        'msg_success_4': '\🟢 *You have successfully deativated the plugin.*',
        'msg_success_5': '\🟢 *You have successfully configured a discord server. You can now configure the server by typing the command.* `.status`',
        'msg_1': '\🗨️ *For more information, type the command* `.status`',
        'msg_error_1': '\🔴 _**{}**_ *channel does not exist on this discordo server.*',
        'msg_error_2': '\🔴 _**{}**_ *plugin not found in system.*',
        'msg_error_3': '\🔴 _**{}**_ *argument not found in system. Please check that you are typing the command correctly and try again.*',
        'msg_error_4': '\🔴 *Change failed. Check that you typed the command correctly.*',
        'msg_error_5': '\🔴 *Module activation failed. Please check the plugin configuration.*',
        'msg_badformat_1': '\🟡 *Invalid format.*\n\🟢 *Example* _**.config channel chat0 #general**_',
        'msg_badformat_2': '\🟡 *Invalid format.*\n\🟢 *Please use configuration tool* *https://origin.clan.su/setup.html*.',
    }
}

vote = {
    'LT': {
        'msg_pool_1': '\📊 *Ar užmutinti narį* _**{}**_?\n*Reikia* _**{}**_ *balsų. Balsavimas baigsis po* _**{}**_ *minučių.*',
        'msg_1': '\🗨️ *Jau vyksta balsavimas dėl nario* {} *užmutinimo!*',
        'msg_2': '\🟢 *Narys* {} *buvo atmutintas.*',
        'msg_3': '\🟢 *Narys* {} *buvo užmutintas iki* **{}.{} - {}:{}**. {}',
        'msg_4': '*Narys gali dabar rašyti tik* <#{}> *skiltyje.*',
        'msg_5': '\🗨️ *Balsavimas baigtas! Narys* {} *nebuvo užmutintas*.',
        'msg_decline': '\🟡 *Narys* {} *jau yra užmutintas*.',
        'msg_badformat': '\🟡 *Netinkamas formatas.*\n\🟢 *Pavyzdys* _**.votemute {}**_',
        'msg_nopermissions': '\🔴 *Jūs neturite* _**{}**_ *rolės, tam, kad naudotis šia komanda.*'
    },
    'EN': {
        'msg_pool_1': '\📊 *Mute member* _**{}**_?\n*Requires* _**{}**_ *votes. The vote will end in* _**{}**_ *minutes.*',
        'msg_1': '\🗨️ *Vote because of* {} *is still going!*',
        'msg_2': '\🟢 *Member* {} *was unmuted.*',
        'msg_3': '\🟢 *Member* {} *was muted until* **{}.{} - {}:{}**. {}',
        'msg_4': ' *Member can only write in* <#{}> *channel.*',
        'msg_5': '\🗨️ *Voting is over! Member* {} *has not been muted*.',
        'msg_decline': '\🟡 *Member* {} *is already muted*.',
        'msg_badformat': '\🟡 *Invalid format.*\n\🟢 *Example* _**.votemute {}**_',
        'msg_nopermissions': '\🔴 *You do not have a* _**{}**_ *role to use this command.*'
    }
}

command_listener = {
    'LT': {
        'help': '{} - Komandos',
        'admin': '{} - Administracijos komandos',
        'about': '{} - Apie projektą'
    },
    'EN': {
        'help': '{} - Commands',
        'admin': '{} - Administration commands',
        'about': '{} - About project'
    }
}

#▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
#SYSTEM

embed_footer = {
    'LT': {
        'embed1': 'Norint sužinoti Origin boto komandas, rašykite komandą .help'
    },
    'EN': {
        'embed1': 'To see the Origin bot commands, type the command .help'
    }
}

user_permissions = {
    'LT': {
        'msg_restricted_1': '\🔴 *Jūs neturite privilegijos naudotis šia komanda.*',
    },
    'EN': {
        'msg_restricted_1': '\🔴 *You do not have privileges to use this command.*',
    }
}

module_permissions = {
    'LT': {
        'msg_noconfig': '\⚙️*Discordo serveryje **{}** pluginas yra nesukonfiguruotas. Norint sužinoti daugiau informacijos, rašykite komandą* `.status`',
        'msg_deactive': '\⚙️*Discordo serveryje **{}** pluginas yra deaktyvuotas. Norint sužinoti daugiau informacijos, rašykite komandą* `.status`',
        'msg_private': '\⚙️**{}** *pluginas yra privatus. Norint sužinoti daugiau informacijos, rašykite komandą* `.private`',
        'msg_restricted': '\🔴 *Ši komanda neveikia šioje skiltyje.*',
        'msg_restricted_pm': '\🔴 *Ši komanda veikia tik discordo serveryje.*'
    },
    'EN': {
        'msg_noconfig': '\⚙️*On this discord server the plugin **{}** is not configured. For more information, type* `.status`',
        'msg_deactive': '\⚙️*On this Discordo server the plugin **{}** is deactivated. For more information, type* `.status`',
        'msg_private': '\⚙️*The plugin **{}** is private. For more information, type* `.private`',
        'msg_restricted': '\🔴 *This command does not work in this channel.*',
        'msg_restricted_pm': '\🔴 *This command only works on the discordo server.*'
    }
}

#▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
#DISCORD PLUGIN ADDONS

DISCORD_TOP = {
    'LT': [
        "Pirmoji vieta",
        "Antroji vieta",
        "Trečioji vieta",
        "Ketvirtoji vieta",
        "Penktoji vieta",
        "Šeštoji vieta",
        "Septintoji vieta",
        "Aštuntoji vieta",
        "Devintoji vieta",
        "Dešimtoji  vieta",
        "Vienuoliktoji vieta",
        "Dvyliktoji vieta",
        "Tryliktoji vieta",
        "Keturioliktoji vieta",
        "Penkioliktoji vieta",
        "Šešiliktoji vieta",
        "Septyniliktoji vieta",
        "Aštuoniliktoji vieta",
        "Devyniliktoji vieta",
        "Dvidešimtoji vieta"
    ],
    'EN': [
        "First place",
        "Second place",
        "Third place",
        "Fourth place",
        "Fifth place",
        "Sixth place",
        "Seventh place",
        "Eighth place",
        "Ninth place",
        "Tenth place",
        "Eleventh Place",
        "Twelfth place",
        "Thirteenth Place",
        "Fourteenth place",
        "Fifteenth place",
        "Sixth place"
        "Seventeenth place",
        "Eighth place",
        "Nineteenth Place",
        "Twentieth place"
    ]
}

DISCORD_EMOTE = {
    'positive': '✅',
    'like': '🙂',
    'thanks': '<:thanks:740105998349500426>',
}
